id: I1B669BA8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:34:38+00:00'
last_modified: '2022-06-09T04:53:39.401467+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30440
  title: བོད་ལྗོངས་རྒྱུན་སྤྱོད་ཀྲུང་དབྱིའི་སྨན་རིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BBBF:
      image_group_id: I1PD30325
      title: Volume 1 of bod ljongs rgyun spyod krung dbyi'i sman rigs
      total_pages: 1322
      order: 1
      base_file: BBBF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
