id: P008156
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:05:05.942948
source_metadata:
  id: bdr:W30440
  title: བོད་ལྗོངས་རྒྱུན་སྤྱོད་ཀྲུང་དབྱིའི་སྨན་རིགས
  author: ''
  volumes:
    ade2d19428064e03bc4c52e4498f5ddd:
      image_group_id: I1PD30325
      title: Volume 1 of bod ljongs rgyun spyod krung dbyi'i sman rigs
      volume_number: 1
      total_pages: 1322
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
