id: P008156
initial_creation_type: ocr
source_metadata:
  id: bdr:W30440
  title: བོད་ལྗོངས་རྒྱུན་སྤྱོད་ཀྲུང་དབྱིའི་སྨན་རིགས
  author: ''
  volumes:
    ba824e46a29548c0ad8be69676a39dea:
      image_group_id: I1PD30325
      title: ''
      volume_number: 1
      total_pages: 1322
ebook_metadata:
  title: བོད་ལྗོངས་རྒྱུན་སྤྱོད་ཀྲུང་དབྱིའི་སྨན་རིགས
  author: ''
  sku: P008156
  cover: cover.jpg
  layers:
  - pagination
